name: release

on:
  release:
    types: [created]

jobs:
  releases-linux-binaries:
    name: Release Go Binaries For Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.15
          extra_files: LICENSE README.md
  releases-macos-binaries:
    name: Release Go Binaries For MacOS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          # It seems golang 1.15 cannot build binary for the platform of darwin/arm64.
          goversion: "https://golang.org/dl/go1.16.5.linux-amd64.tar.gz"
          extra_files: LICENSE README.md